kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-member-api
  namespace: dev-tehs-test
  uid: cb9d3e32-e7f3-498f-887d-9defcbf81d88
  resourceVersion: '727500299'
  generation: 115
  creationTimestamp: '2024-12-11T05:59:15Z'
  annotations:
    deployment.kubernetes.io/revision: '103'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2025-04-22T03:12:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.openshift.io/restartedAt': {}
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"app"}':
                  'f:image': {}
                  'f:startupProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/app/appsettings.json"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:subPath': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"testAuthSettings__JwtPublicKey"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ConnectionStrings__testET1_Read"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"ConnectionStrings__Fugo"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    .: {}
                    'k:{"name":"HOST_POD_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef': {}
                    'k:{"name":"ASPNETCORE_HTTP_PORTS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"OTEL_EXPORTER_OTLP_ENDPOINT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"HEADER_FORWARDED_LIMIT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ConnectionStrings__tehsn"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"OTEL_EXPORTER_OTLP_PROTOCOL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"HOST_NODE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef': {}
                    'k:{"name":"ASPNETCORE_ENVIRONMENT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"OTEL_SERVICE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ConnectionStrings__Redis"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"InfrastructureSettings__HashKey"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"ConnectionStrings__testET1_Write"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
                'k:{"name":"otel-collector"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/etc/otelcol-contrib/config.yaml"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:subPath': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":4317,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"app-config-volume"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:items': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"otel-config-volume"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:items': {}
                    'f:name': {}
                  'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-04-22T03:12:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-member-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-member-api
      annotations:
        openshift.openshift.io/restartedAt: '2025-04-22T03:12:19.750Z'
    spec:
      volumes:
        - name: app-config-volume
          configMap:
            name: test-api-configuration
            items:
              - key: member-api-appsettings
                path: appsettings.json
            defaultMode: 420
        - name: otel-config-volume
          configMap:
            name: test-otel-configuration
            items:
              - key: member-api-otelcol-config
                path: config.yaml
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          name: app
          livenessProbe:
            httpGet:
              path: /hc/live
              port: app-port
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: TZ
              value: Asia/Taipei
            - name: ASPNETCORE_HTTP_PORTS
              value: '8080'
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: HEADER_FORWARDED_LIMIT
              value: '2'
            - name: OTEL_SERVICE_NAME
              value: member-api
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://localhost:4317'
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: delta
            - name: HOST_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOST_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: testAuthSettings__JwtPublicKey
              valueFrom:
                secretKeyRef:
                  name: test-jwt-settings
                  key: PublicKey
            - name: InfrastructureSettings__HashKey
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: HashKey
            - name: ConnectionStrings__testET1_Read
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: testET1_Read
            - name: ConnectionStrings__testET1_Write
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: testET1_Write
            - name: ConnectionStrings__Fugo
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: Fugo
            - name: ConnectionStrings__tehsn
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: tehsn
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: Redis
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /hc/live
              port: app-port
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          volumeMounts:
            - name: app-config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          terminationMessagePolicy: File
          image: 'sit-quay.testzone.net/dev-tehs-test/test-member-api:latest'
        - name: otel-collector
          image: >-
            sit-quay.testzone.net/dev-tehs-test/opentelemetry-collector-contrib:0.122.1
          ports:
            - containerPort: 4317
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 700Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: otel-config-volume
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
status:
  observedGeneration: 115
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-04-17T02:41:25Z'
      lastTransitionTime: '2025-04-17T02:41:25Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-04-22T03:12:25Z'
      lastTransitionTime: '2025-03-25T07:40:21Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "test-member-api-657c94859f" has successfully progressed.
